/* Minimal text extractor for the CEO Karnataka ASDDO booth PDFs.
   These are machine-generated by one ECI tool: no scanned images, base-14
   fonts, and every table cell is its own positioned `BT … x y Td (text) Tj ET`
   block. That makes a full PDF library unnecessary — and a dependency-free
   extractor is one less thing to break.

   Cells are matched to columns by x-coordinate rather than by counting tokens.
   Counting looks fine on a clean sample and then quietly corrupts every row
   that has a blank cell or a wrapped one: the offsets slide, and a relative's
   name ends up in the reason column. Geometry does not slide. */

import { inflateSync, unzipSync } from 'node:zlib';

/** Every drawn string with its page position, in drawing order. */
export function extractItems(buf) {
  const streams = [];
  const START = Buffer.from('stream');
  const END = Buffer.from('endstream');
  let from = 0;
  for (;;) {
    const s = buf.indexOf(START, from);
    if (s === -1) break;
    const e = buf.indexOf(END, s);
    if (e === -1) break;
    let a = s + START.length;
    if (buf[a] === 0x0d) a++;
    if (buf[a] === 0x0a) a++;
    let b = e;
    if (buf[b - 1] === 0x0a) b--;
    if (buf[b - 1] === 0x0d) b--;
    streams.push(buf.subarray(a, b));
    from = e + END.length;
  }

  const pages = [];
  for (const raw of streams) {
    let data = raw;
    if (raw[0] === 0x78) {
      try {
        data = inflateSync(raw);
      } catch {
        try {
          data = unzipSync(raw);
        } catch {
          continue; // an image or a filter we don't handle
        }
      }
    }
    const items = parseContentStream(data.toString('latin1'));
    if (items.length) pages.push(items);
  }
  return pages;
}

// This generator emits trailing-dot numbers (`25.`, `0.`) as well as the usual
// forms, so the pattern has to accept an empty fractional part.
const NUM = '-?(?:\\d+\\.?\\d*|\\.\\d+)';
const OPS = new RegExp(
  [
    `(${NUM})\\s+(${NUM})\\s+Td`,                                    // 1,2   move
    `(${NUM})\\s+(${NUM})\\s+TD`,                                    // 3,4   move + set leading
    `(?:${NUM}\\s+){4}(${NUM})\\s+(${NUM})\\s+Tm`,                   // 5,6   absolute
    `(${NUM})\\s+TL`,                                                // 7     leading
    `\\(((?:[^()\\\\]|\\\\[\\s\\S])*)\\)\\s*Tj`,                     // 8     show
    `\\[((?:[^\\[\\]\\\\]|\\\\[\\s\\S])*)\\]\\s*TJ`,                 // 9     show array
    `(BT|ET|T\\*)`                                                   // 10    block / newline
  ].join('|'),
  'g'
);

function parseContentStream(text) {
  const items = [];
  let x = 0;
  let y = 0;
  let leading = 0;
  let m;
  OPS.lastIndex = 0;
  while ((m = OPS.exec(text)) !== null) {
    if (m[1] !== undefined) { x += +m[1]; y += +m[2]; }
    else if (m[3] !== undefined) { leading = -m[4]; x += +m[3]; y += +m[4]; }
    else if (m[5] !== undefined) { x = +m[5]; y = +m[6]; }
    else if (m[7] !== undefined) { leading = +m[7]; }
    else if (m[8] !== undefined) { push(unescapePdfString(m[8])); }
    else if (m[9] !== undefined) {
      // [(a) -250 (b)] TJ — concatenate the string parts, drop the kerning.
      const parts = [...m[9].matchAll(/\(((?:[^()\\]|\\[\s\S])*)\)/g)].map((p) => p[1]);
      push(unescapePdfString(parts.join('')));
    } else if (m[10] === 'BT') { x = 0; y = 0; }
    else if (m[10] === 'T*') { y -= leading; }
  }

  function push(str) {
    if (str) items.push({ x, y, text: str });
  }
  return items;
}

function unescapePdfString(s) {
  return s
    .replace(/\\([0-7]{1,3})/g, (_, o) => String.fromCharCode(parseInt(o, 8)))
    .replace(/\\n/g, ' ')
    .replace(/\\r/g, ' ')
    .replace(/\\t/g, ' ')
    .replace(/\\([()\\])/g, '$1')
    .replace(/\s+/g, ' ')
    .trim();
}

export const EPIC_RE = /^[A-Z]{3}[0-9]{7}$/;

/** True when the PDF is a scan we cannot read as text. */
export function looksScanned(buf) {
  const head = buf.toString('latin1');
  return /\/Subtype\s*\/Image/.test(head) && !/\)\s*Tj/.test(head);
}

const COLUMNS = [
  { key: 'sno', header: 'S.No.' },
  { key: 'serial', header: 'Serial No.' },
  { key: 'epic', header: 'EPIC Number' },
  { key: 'name', header: 'Elector Name' },
  { key: 'relative', header: 'Relative Details' },
  { key: 'dobAge', header: 'DOB/Age' },
  { key: 'reason', header: 'Uncollectable Reason' }
];

/** Group items that share a baseline into one visual row, top of page first. */
function toRows(items, tolerance = 1.5) {
  const rows = [];
  for (const item of [...items].sort((a, b) => b.y - a.y || a.x - b.x)) {
    const last = rows[rows.length - 1];
    if (last && Math.abs(last.y - item.y) <= tolerance) last.cells.push(item);
    else rows.push({ y: item.y, cells: [item] });
  }
  for (const row of rows) row.cells.sort((a, b) => a.x - b.x);
  return rows;
}

/** Turn a booth PDF into rows. */
export function parseBoothPdf(buf) {
  const pages = extractItems(buf);
  const out = [];
  const meta = {};
  let unreadablePages = 0;

  for (const items of pages) {
    const rows = toRows(items);

    for (const row of rows) {
      const line = row.cells.map((c) => c.text).join(' ');
      if (!meta.acLine && /^AC:\s*/.test(line)) meta.acLine = line;
      if (!meta.generatedOn) {
        const g = /Date of Generation:\s*([\d/]+)/.exec(line);
        if (g) meta.generatedOn = g[1];
      }
    }

    // Column x-positions come from this page's own header, because the
    // generator sizes columns to fit the widest value on the page.
    const header = findHeader(rows);
    if (!header) {
      unreadablePages++;
      continue;
    }
    const { headerRow, anchors } = header;

    let current = null;
    const flush = () => {
      if (current && EPIC_RE.test(current.epic ?? '')) out.push(finaliseRow(current));
      current = null;
    };

    for (const row of rows) {
      if (row.y >= headerRow.y) continue; // header and anything above it
      const cells = assign(row.cells, anchors);

      // Footer lines sit in the left-most column and are not numbered.
      const first = row.cells[0]?.text ?? '';
      if (/^(Date of Generation|Generated by|Note:|AC:|Page\b|View Enumeration)/i.test(first)) {
        flush();
        continue;
      }

      if (/^\d+$/.test(cells.sno ?? '') && EPIC_RE.test(cells.epic ?? '')) {
        flush();
        current = cells;
      } else if (current) {
        // A wrapped cell: same columns, next baseline, no new S.No.
        for (const key of Object.keys(cells)) {
          if (cells[key]) current[key] = `${current[key] ?? ''} ${cells[key]}`.trim();
        }
      }
    }
    flush();
  }

  return { rows: out, meta, unreadablePages };
}

/**
 * Locate the column header and read the x-position of each column off it.
 *
 * A header label is not reliably one text object: some booths draw
 * "Serial No." as `Serial` + `No.`, and a narrow column can push a label onto
 * a second baseline. So instead of matching cell text exactly, walk the row
 * left to right accumulating cells until the buffer completes the next
 * expected label — the anchor is the x of the group's first cell.
 */
function findHeader(rows) {
  const norm = (s) => s.toLowerCase().replace(/[^a-z]/g, '');
  const wanted = COLUMNS.map((c) => norm(c.header));

  for (let i = 0; i < rows.length; i++) {
    // Allow the header to occupy up to two baselines.
    for (const span of [1, 2]) {
      const cells = rows
        .slice(i, i + span)
        .flatMap((r) => r.cells)
        .sort((a, b) => a.x - b.x);
      if (!cells.length) continue;

      const anchors = [];
      let want = 0;
      let buffer = '';
      let startX = null;
      for (const cell of cells) {
        if (want >= wanted.length) break;
        if (startX === null) startX = cell.x;
        buffer += norm(cell.text);
        if (buffer === wanted[want]) {
          anchors.push({ ...COLUMNS[want], x: startX });
          want++;
          buffer = '';
          startX = null;
        } else if (!wanted[want].startsWith(buffer)) {
          // Not part of this label after all — restart from this cell.
          buffer = norm(cell.text);
          startX = cell.x;
          if (buffer === wanted[want]) {
            anchors.push({ ...COLUMNS[want], x: startX });
            want++;
            buffer = '';
            startX = null;
          }
        }
      }

      // The five columns the parser actually reads must all be present.
      const keys = new Set(anchors.map((a) => a.key));
      if (['sno', 'serial', 'epic', 'name', 'reason'].every((k) => keys.has(k))) {
        return { headerRow: rows[i + span - 1], anchors };
      }
    }
  }
  return null;
}

/** Nearest-anchor assignment, so a blank cell shifts nothing. */
function assign(cells, anchors) {
  const result = {};
  for (const cell of cells) {
    let best = anchors[0];
    let bestDist = Infinity;
    for (const anchor of anchors) {
      // Cells are left-aligned in their column, so a cell belongs to the
      // nearest anchor at or to the left of it.
      const dist = cell.x >= anchor.x - 2 ? cell.x - anchor.x : (anchor.x - cell.x) * 4;
      if (dist < bestDist) {
        bestDist = dist;
        best = anchor;
      }
    }
    result[best.key] = result[best.key] ? `${result[best.key]} ${cell.text}` : cell.text;
  }
  return result;
}

function finaliseRow(cells) {
  const relative = cells.relative ?? '';
  const dobAge = cells.dobAge ?? '';
  const reason = (cells.reason ?? '').replace(/\s+/g, ' ').trim();

  const relMatch = /\(([^)]+)\)\s*$/.exec(relative);
  const ageMatch = /\((\d{1,3})\)/.exec(dobAge);
  const dobMatch = /(\d{2}[/-]\d{2}[/-]\d{4})/.exec(dobAge);
  const dupMatch = /\(([A-Z]{3}\d{7})\)/.exec(reason);

  return {
    serial: /^\d+$/.test(cells.serial ?? '') ? +cells.serial : null,
    epic: cells.epic,
    name: (cells.name ?? '').replace(/\s+/g, ' ').trim(),
    relative: relative.replace(/\s*\([^)]*\)\s*$/, '').replace(/\s+/g, ' ').trim(),
    relation: relMatch ? relMatch[1].trim() : '',
    age: ageMatch ? +ageMatch[1] : null,
    dob: dobMatch ? dobMatch[1] : '',
    reasonRaw: reason,
    category: categorise(reason),
    dupEpic: dupMatch ? dupMatch[1] : ''
  };
}

/**
 * The PDFs never print the letters A/S/D/D/O — they print prose. This is the
 * mapping back onto the five official ASDDO buckets. Anything unrecognised
 * lands in `others` rather than being dropped, and 3-extract reports the
 * unmapped strings so new wording gets noticed instead of silently misfiled.
 */
export function categorise(reasonRaw) {
  const r = (reasonRaw || '').toLowerCase();
  if (!r) return 'others';
  if (/already enrolled|duplicate|repeat/.test(r)) return 'duplicate';
  if (/death|dead|expired|deceased/.test(r)) return 'death';
  // "Permanently" on its own shows up when the cell wraps awkwardly; the only
  // reason string in this dataset beginning that way is "Permanently Shifted".
  if (/shift|migrat|moved|permanent/.test(r)) return 'shifted';
  if (/absent|untrace|not found|non-?resident/.test(r)) return 'absent';
  return 'others';
}

export const CATEGORIES = ['absent', 'shifted', 'death', 'duplicate', 'others'];
